spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.23.129
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
